# Generated by Django 3.0.3 on 2020-02-22 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0008_auto_20200222_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='empresa',
        ),
    ]
