# Generated by Django 3.0.3 on 2020-02-22 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_empresa_funcionario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='funcionario',
        ),
    ]
