# Generated by Django 3.0.3 on 2020-02-24 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0002_departamentos_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamentos',
            name='empresa',
        ),
    ]
