# Generated by Django 3.0.3 on 2020-02-24 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_remove_empresa_funcionario'),
        ('departamentos', '0003_remove_departamentos_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamentos',
            name='empresa',
            field=models.ForeignKey(default=22, on_delete=django.db.models.deletion.PROTECT, to='empresas.Empresa'),
            preserve_default=False,
        ),
    ]
